"""add signer

Revision ID: 00c934212d6f
Revises: 994dfe65b9d8
Create Date: 2022-04-21 07:33:15.751703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c934212d6f'
down_revision = '994dfe65b9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=True),
    sa.Column('fullNameRu', sa.String(), nullable=True),
    sa.Column('fullNameKz', sa.String(), nullable=True),
    sa.Column('positionRu', sa.String(), nullable=True),
    sa.Column('positionKz', sa.String(), nullable=True),
    sa.Column('departmentRu', sa.String(), nullable=True),
    sa.Column('departmentKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signer_id'), 'signer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signer_id'), table_name='signer')
    op.drop_table('signer')
    # ### end Alembic commands ###
