"""empty message

Revision ID: 015be2e183f6
Revises: a046001aaf10
Create Date: 2022-04-21 15:24:51.521288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015be2e183f6'
down_revision = 'a046001aaf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signDate', sa.DateTime(), nullable=True),
    sa.Column('certStartDate', sa.DateTime(), nullable=True),
    sa.Column('certEndtDate', sa.DateTime(), nullable=True),
    sa.Column('certOwner', sa.String(), nullable=True),
    sa.Column('PUID', sa.String(), nullable=True),
    sa.Column('cert', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('signedFieldsSequence', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('signedFilesIdSequence', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('providerTypeId', sa.Integer(), nullable=True),
    sa.Column('signatureId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['providerTypeId'], ['eds_provider_type.id'], ),
    sa.ForeignKeyConstraint(['signatureId'], ['signature.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eds_id'), 'eds', ['id'], unique=False)
    op.create_table('signature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decreeId', sa.Integer(), nullable=True),
    sa.Column('resolutionId', sa.Integer(), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=True),
    sa.Column('signDate', sa.DateTime(), nullable=True),
    sa.Column('signerId', sa.Integer(), nullable=True),
    sa.Column('replacedId', sa.Integer(), nullable=True),
    sa.Column('edsId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decreeId'], ['decree.id'], ),
    sa.ForeignKeyConstraint(['edsId'], ['eds.id'], ),
    sa.ForeignKeyConstraint(['replacedId'], ['signature_replaced.id'], ),
    sa.ForeignKeyConstraint(['resolutionId'], ['signature_resolution.id'], ),
    sa.ForeignKeyConstraint(['signerId'], ['signer.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['signature_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_id'), 'signature', ['id'], unique=False)
    op.create_table('signature_replaced',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=True),
    sa.Column('fullNameRu', sa.String(), nullable=True),
    sa.Column('fullNameKz', sa.String(), nullable=True),
    sa.Column('positionRu', sa.String(), nullable=True),
    sa.Column('positionKz', sa.String(), nullable=True),
    sa.Column('departmentRu', sa.String(), nullable=True),
    sa.Column('departmentKz', sa.String(), nullable=True),
    sa.Column('replacementTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['replacementTypeId'], ['replacement_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_replaced_id'), 'signature_replaced', ['id'], unique=False)
    op.add_column('signer', sa.Column('nameRu', sa.String(), nullable=True))
    op.add_column('signer', sa.Column('nameKz', sa.String(), nullable=True))
    op.drop_column('signer', 'employeeId')
    op.drop_column('signer', 'positionKz')
    op.drop_column('signer', 'fullNameKz')
    op.drop_column('signer', 'fullNameRu')
    op.drop_column('signer', 'positionRu')
    op.drop_column('signer', 'departmentRu')
    op.drop_column('signer', 'departmentKz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signer', sa.Column('departmentKz', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signer', sa.Column('departmentRu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signer', sa.Column('positionRu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signer', sa.Column('fullNameRu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signer', sa.Column('fullNameKz', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signer', sa.Column('positionKz', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signer', sa.Column('employeeId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('signer', 'nameKz')
    op.drop_column('signer', 'nameRu')
    op.drop_index(op.f('ix_signature_replaced_id'), table_name='signature_replaced')
    op.drop_table('signature_replaced')
    op.drop_index(op.f('ix_signature_id'), table_name='signature')
    op.drop_table('signature')
    op.drop_index(op.f('ix_eds_id'), table_name='eds')
    op.drop_table('eds')
    # ### end Alembic commands ###
