"""empty message

Revision ID: 2ca7d27c0d32
Revises: 5174533c78bd
Create Date: 2022-04-22 05:34:36.993877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ca7d27c0d32'
down_revision = '5174533c78bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eds', sa.Column('certEndDate', sa.DateTime(), nullable=True))
    op.drop_column('eds', 'certEndtDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eds', sa.Column('certEndtDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('eds', 'certEndDate')
    # ### end Alembic commands ###
