"""empty message

Revision ID: 5174533c78bd
Revises: 079ad0f968d7
Create Date: 2022-04-21 15:43:30.318165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5174533c78bd'
down_revision = '079ad0f968d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signature', sa.Column('isActive', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signature', 'isActive')
    # ### end Alembic commands ###
