"""add signature_resolution

Revision ID: 5825543c425c
Revises: f5241f16420b
Create Date: 2022-04-21 07:09:02.574800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5825543c425c'
down_revision = 'f5241f16420b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_resolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_resolution_id'), 'signature_resolution', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_resolution_id'), table_name='signature_resolution')
    op.drop_table('signature_resolution')
    # ### end Alembic commands ###
