"""empty message

Revision ID: 7ff4dffbf0e6
Revises: db0b384ade61
Create Date: 2022-04-22 06:22:51.624353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff4dffbf0e6'
down_revision = 'db0b384ade61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eds', sa.Column('signedFilesIdSequence', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eds', 'signedFilesIdSequence')
    # ### end Alembic commands ###
