"""add decree kind

Revision ID: 994dfe65b9d8
Revises: d427d47a062b
Create Date: 2022-04-21 07:24:29.388698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994dfe65b9d8'
down_revision = 'd427d47a062b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decree_kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decree_kind_id'), 'decree_kind', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decree_kind_id'), table_name='decree_kind')
    op.drop_table('decree_kind')
    # ### end Alembic commands ###
