"""Add decree

Revision ID: a046001aaf10
Revises: 2b4f135070e3
Create Date: 2022-04-21 13:54:01.796693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a046001aaf10'
down_revision = '2b4f135070e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('mainId', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.Column('typeId', sa.Integer(), nullable=True),
    sa.Column('changeTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changeTypeId'], ['decree_change_action.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['decree_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decree_id'), 'decree', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decree_id'), table_name='decree')
    op.drop_table('decree')
    # ### end Alembic commands ###
