"""add signature type

Revision ID: d427d47a062b
Revises: e3c1a38ff38a
Create Date: 2022-04-21 07:18:30.215808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd427d47a062b'
down_revision = 'e3c1a38ff38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_type_id'), 'signature_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_type_id'), table_name='signature_type')
    op.drop_table('signature_type')
    # ### end Alembic commands ###
