"""empty message

Revision ID: db0b384ade61
Revises: 1f75e3a79b3a
Create Date: 2022-04-22 06:22:18.225622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db0b384ade61'
down_revision = '1f75e3a79b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eds', 'signedFilesIdSequence')
    op.add_column('signer', sa.Column('employeeId', sa.Integer(), nullable=True))
    op.add_column('signer', sa.Column('fullNameRu', sa.String(), nullable=True))
    op.add_column('signer', sa.Column('fullNameKz', sa.String(), nullable=True))
    op.add_column('signer', sa.Column('positionRu', sa.String(), nullable=True))
    op.add_column('signer', sa.Column('positionKz', sa.String(), nullable=True))
    op.add_column('signer', sa.Column('departmentRu', sa.String(), nullable=True))
    op.add_column('signer', sa.Column('departmentKz', sa.String(), nullable=True))
    op.drop_column('signer', 'nameRu')
    op.drop_column('signer', 'nameKz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signer', sa.Column('nameKz', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('signer', sa.Column('nameRu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('signer', 'departmentKz')
    op.drop_column('signer', 'departmentRu')
    op.drop_column('signer', 'positionKz')
    op.drop_column('signer', 'positionRu')
    op.drop_column('signer', 'fullNameKz')
    op.drop_column('signer', 'fullNameRu')
    op.drop_column('signer', 'employeeId')
    op.add_column('eds', sa.Column('signedFilesIdSequence', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
