"""add decree_change_action

Revision ID: e3c1a38ff38a
Revises: 5825543c425c
Create Date: 2022-04-21 07:14:15.940486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c1a38ff38a'
down_revision = '5825543c425c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decree_change_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decree_change_action_id'), 'decree_change_action', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decree_change_action_id'), table_name='decree_change_action')
    op.drop_table('decree_change_action')
    # ### end Alembic commands ###
