"""Add counter

Revision ID: e5833da0286c
Revises: 00c934212d6f
Create Date: 2022-04-21 08:21:22.888653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5833da0286c'
down_revision = '00c934212d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_id'), 'counter', ['id'], unique=False)
    op.create_table('replacement_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameRu', sa.String(), nullable=True),
    sa.Column('nameKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replacement_type_id'), 'replacement_type', ['id'], unique=False)
    op.create_table('signer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=True),
    sa.Column('fullNameRu', sa.String(), nullable=True),
    sa.Column('fullNameKz', sa.String(), nullable=True),
    sa.Column('positionRu', sa.String(), nullable=True),
    sa.Column('positionKz', sa.String(), nullable=True),
    sa.Column('departmentRu', sa.String(), nullable=True),
    sa.Column('departmentKz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signer_id'), 'signer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signer_id'), table_name='signer')
    op.drop_table('signer')
    op.drop_index(op.f('ix_replacement_type_id'), table_name='replacement_type')
    op.drop_table('replacement_type')
    op.drop_index(op.f('ix_counter_id'), table_name='counter')
    op.drop_table('counter')
    # ### end Alembic commands ###
